apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: app-user
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: orders
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
          - Create
      - resource:
          type: group
          name: webstore-consumer-group
          patternType: literal
        operations:
          - Read
      - resource:
          type: cluster
        operations:
          - Describe

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: console-user
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
          - Create
          - Delete
          - Alter
          - DescribeConfigs
          - AlterConfigs
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - Read
          - Describe
      - resource:
          type: cluster
        operations:
          - Create
          - Describe
          - Alter
          - IdempotentWrite
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operations:
          - Describe
          - Write
